title: ROLE DOCUMENT FRAME
mdn_url: /ja/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_DOCUMENT_FRAME
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_DOCUMENT_FRAME
locale: ja
modified: 2019-04-25T13:06:18.519Z
mdn_contributors:
  - wbamberg
  - mdnwebdocs-bot
  - Uemmra3
  - shide55
parent:
  slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_DOCUMENT_FRAME
  locale: en-US
  modified: 2019-04-23T14:02:35.136Z
