title: Gecko Roles
mdn_url: /en-US/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles
locale: en-US
modified: 2019-04-23T14:02:31.114Z
mdn_contributors:
  - wbamberg
  - ExE-Boss
  - mdnwebdocs-bot
  - Fredchat
  - Sheppy
  - fscholz
  - Surkov.alexander
  - Mgjbot
  - Michael Evil
