title: ROLE_CURSOR
mdn_url: /ja/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_CURSOR
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_CURSOR
locale: ja
modified: 2019-04-25T13:07:44.335Z
mdn_contributors:
  - wbamberg
  - mdnwebdocs-bot
  - Marsf
  - shide55
parent:
  slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_CURSOR
  locale: en-US
  modified: 2019-04-23T14:04:13.270Z
