title: ROLE_BUTTONDROPDOWN
mdn_url: /ja/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_BUTTONDROPDOWN
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_BUTTONDROPDOWN
locale: ja
modified: 2019-04-25T13:07:12.090Z
mdn_contributors:
  - wbamberg
  - mdnwebdocs-bot
  - Uemmra3
  - shide55
parent:
  slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_BUTTONDROPDOWN
  locale: en-US
  modified: 2019-04-23T14:03:36.311Z
