title: ROLE_WINDOW
mdn_url: /en-US/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_WINDOW
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_WINDOW
locale: en-US
modified: 2019-04-23T14:06:04.633Z
mdn_contributors:
  - wbamberg
  - ExE-Boss
  - mdnwebdocs-bot
  - Sheppy
  - Surkov.alexander
