title: ROLE PASSWORD TEXT
mdn_url: /fr/docs/Web/Accessibility/AT-APIs/Gecko/Roles/ROLE_PASSWORD_TEXT
slug: Web/Accessibility/AT-APIs/Gecko/Roles/ROLE_PASSWORD_TEXT
locale: fr
modified: 2019-04-25T13:12:40.520Z
mdn_contributors:
  - wbamberg
  - mdnwebdocs-bot
  - dragon38800
parent:
  slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_PASSWORD_TEXT
  locale: en-US
  modified: 2019-04-23T14:03:04.679Z
