title: 'ARIA: checkbox role'
mdn_url: /ru/docs/Web/Accessibility/ARIA/Roles/checkbox_role
slug: Web/Accessibility/ARIA/Roles/checkbox_role
locale: ru
modified: 2019-03-19T06:13:31.955Z
mdn_contributors:
  - viktoryiakuzmitskaya
parent:
  slug: Web/Accessibility/ARIA/Roles/checkbox_role
  locale: en-US
  modified: 2019-06-12T04:02:22.486Z
