title: 'ARIA: figure role'
mdn_url: /en-US/docs/Web/Accessibility/ARIA/Roles/Figure_Role
slug: Web/Accessibility/ARIA/Roles/Figure_Role
locale: en-US
modified: 2019-06-12T04:00:34.077Z
mdn_contributors:
  - chrisdavidmills
  - PickensC
  - kospl
  - mdnwebdocs-bot
  - mrshannonyoung
  - estelle
  - jswisher
