title: 'ARIA: tab role'
mdn_url: /en-US/docs/Web/Accessibility/ARIA/Roles/Tab_Role
slug: Web/Accessibility/ARIA/Roles/Tab_Role
locale: en-US
modified: 2019-09-04T05:54:33.835Z
mdn_contributors:
  - immerMeer
  - chrisdavidmills
  - estelle
  - Snugug
  - mdnwebdocs-bot
  - Moiety
