title: ROLE_CHART
mdn_url: /ja/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_CHART
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_CHART
locale: ja
modified: 2019-04-25T13:07:25.521Z
mdn_contributors:
  - wbamberg
  - mdnwebdocs-bot
  - Marsf
  - shide55
parent:
  slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_CHART
  locale: en-US
  modified: 2019-04-23T14:03:53.369Z
