title: ROLE_TABLE
mdn_url: /en-US/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_TABLE
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_TABLE
locale: en-US
modified: 2019-04-23T14:05:48.574Z
mdn_contributors:
  - wbamberg
  - ExE-Boss
  - mdnwebdocs-bot
  - Sheppy
  - Surkov.alexander
  - Michael Evil
