title: ROLE_BUTTONMENU
mdn_url: /en-US/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_BUTTONMENU
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_BUTTONMENU
locale: en-US
modified: 2019-04-23T14:03:39.855Z
mdn_contributors:
  - wbamberg
  - ExE-Boss
  - mdnwebdocs-bot
  - Sheppy
  - Michael Evil
