title: ROLE_OUTLINE
mdn_url: /en-US/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_OUTLINE
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_OUTLINE
locale: en-US
modified: 2019-04-23T14:05:09.419Z
mdn_contributors:
  - wbamberg
  - ExE-Boss
  - mdnwebdocs-bot
  - Sheppy
  - Michael Evil
