title: WAI-ARIA Roles
mdn_url: /ru/docs/Web/Accessibility/ARIA/Roles
slug: Web/Accessibility/ARIA/Roles
locale: ru
modified: 2019-03-19T06:13:31.021Z
mdn_contributors:
  - mdnwebdocs-bot
parent:
  slug: Web/Accessibility/ARIA/Roles
  locale: en-US
  modified: 2019-09-05T06:04:56.508Z
