title: 'ARIA: switch role'
mdn_url: /en-US/docs/Web/Accessibility/ARIA/Roles/Switch_role
slug: Web/Accessibility/ARIA/Roles/Switch_role
locale: en-US
modified: 2019-11-01T04:24:57.527Z
mdn_contributors:
  - luciorubeens
  - nstefano
  - chrisdavidmills
  - bradyhullopeter
  - mdnwebdocs-bot
  - YuriiKarmazin
  - estelle
  - jswisher
  - alastc
  - fscholz
  - scottaohara
  - access-sandeep
  - Sheppy
  - teoli
