title: 翻訳ドライバの役割
mdn_url: /ja/docs/MDN/Community/Roles/Localization_driver_role
slug: MDN/Community/Roles/Localization_driver_role
locale: ja
modified: 2019-03-23T17:41:22.600Z
mdn_contributors:
  - mdnwebdocs-bot
  - silverskyvicto
  - wbamberg
  - yyss
  - hamasaki
  - lv7777
parent:
  slug: MDN/Community/Roles/Localization_driver_role
  locale: en-US
  modified: 2019-03-23T18:17:01.872Z
