title: ROLE_TABLE_COLUMN_HEADER
mdn_url: >-
  /ja/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_TABLE_COLUMN_HEADER
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_TABLE_COLUMN_HEADER
locale: ja
modified: 2019-04-25T13:09:19.830Z
mdn_contributors:
  - wbamberg
  - mdnwebdocs-bot
  - shide55
parent:
  slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_TABLE_COLUMN_HEADER
  locale: en-US
  modified: 2019-04-23T14:05:50.228Z
