title: 'ARIA: row ロール'
mdn_url: /ja/docs/Web/Accessibility/ARIA/Roles/Row_Role
slug: Web/Accessibility/ARIA/Roles/Row_Role
locale: ja
modified: 2019-03-18T16:22:17.603Z
mdn_contributors:
  - mdnwebdocs-bot
  - Wind1808
parent:
  slug: Web/Accessibility/ARIA/Roles/Row_Role
  locale: en-US
  modified: 2019-06-12T03:58:08.990Z
