title: ROLE_MENUITEM
mdn_url: /en-US/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_MENUITEM
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_MENUITEM
locale: en-US
modified: 2019-04-23T14:05:02.896Z
mdn_contributors:
  - wbamberg
  - ExE-Boss
  - mdnwebdocs-bot
  - Sheppy
  - Surkov.alexander
