title: 'ARIA: img role'
mdn_url: /ko/docs/Web/Accessibility/ARIA/Roles/Role_Img
slug: Web/Accessibility/ARIA/Roles/Role_Img
locale: ko
modified: 2019-03-18T15:55:03.747Z
mdn_contributors:
  - mdnwebdocs-bot
  - seokju-na
parent:
  slug: Web/Accessibility/ARIA/Roles/Role_Img
  locale: en-US
  modified: 2020-01-01T02:39:03.874Z
