title: ROLE FOOTER
mdn_url: /en-US/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_FOOTER
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_FOOTER
locale: en-US
modified: 2019-04-23T14:02:39.992Z
mdn_contributors:
  - wbamberg
  - ExE-Boss
  - Sheppy
  - Michael Evil
