title: ROLE_ANIMATION
mdn_url: /ja/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_ANIMATION
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_ANIMATION
locale: ja
modified: 2019-04-25T13:07:02.871Z
mdn_contributors:
  - wbamberg
  - mdnwebdocs-bot
  - Uemmra3
  - shide55
parent:
  slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_ANIMATION
  locale: en-US
  modified: 2019-04-23T14:03:25.372Z
