title: 'ARIA: Navigation Role'
mdn_url: /pt-BR/docs/Web/Accessibility/ARIA/Roles/Navigation_Role
slug: Web/Accessibility/ARIA/Roles/Navigation_Role
locale: pt-BR
modified: 2019-09-09T01:56:54.210Z
mdn_contributors:
  - brunopulis
parent:
  slug: Web/Accessibility/ARIA/Roles/Navigation_Role
  locale: en-US
  modified: 2019-07-16T03:09:44.653Z
