title: ROLE_SEPARATOR
mdn_url: /ja/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_SEPARATOR
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_SEPARATOR
locale: ja
modified: 2019-04-25T13:09:06.768Z
mdn_contributors:
  - wbamberg
  - mdnwebdocs-bot
  - Marsf
  - shide55
parent:
  slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_SEPARATOR
  locale: en-US
  modified: 2019-04-23T14:05:35.595Z
