title: ROLE_ROOT_PANE
mdn_url: /en-US/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_ROOT_PANE
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_ROOT_PANE
locale: en-US
modified: 2019-04-23T14:05:29.365Z
mdn_contributors:
  - wbamberg
  - ExE-Boss
  - mdnwebdocs-bot
  - Sheppy
  - Michael Evil
