title: 'ARIA: application role'
mdn_url: /en-US/docs/Web/Accessibility/ARIA/Roles/Application_Role
slug: Web/Accessibility/ARIA/Roles/Application_Role
locale: en-US
modified: 2019-06-12T04:03:49.630Z
mdn_contributors:
  - chrisdavidmills
  - PickensC
  - mdnwebdocs-bot
  - estelle
  - jswisher
  - MarcoZ
