title: WAI-ARIA Roles
mdn_url: /pt-BR/docs/Web/Accessibility/ARIA/Roles
slug: Web/Accessibility/ARIA/Roles
locale: pt-BR
modified: 2019-04-10T08:14:47.528Z
mdn_contributors:
  - rafaelcavalcante
parent:
  slug: Web/Accessibility/ARIA/Roles
  locale: en-US
  modified: 2019-09-05T06:04:56.508Z
