title: ROLE_STATUSBAR
mdn_url: /ja/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_STATUSBAR
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_STATUSBAR
locale: ja
modified: 2019-04-25T13:09:16.196Z
mdn_contributors:
  - wbamberg
  - mdnwebdocs-bot
  - Marsf
  - shide55
parent:
  slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_STATUSBAR
  locale: en-US
  modified: 2019-04-23T14:05:46.861Z
