title: ROLE FORM
mdn_url: /ja/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_FORM
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_FORM
locale: ja
modified: 2019-04-25T13:06:25.506Z
mdn_contributors:
  - wbamberg
  - mdnwebdocs-bot
  - Uemmra3
  - shide55
parent:
  slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_FORM
  locale: en-US
  modified: 2019-04-23T14:02:41.623Z
