title: 'ARIA: banner role'
mdn_url: /en-US/docs/Web/Accessibility/ARIA/Roles/Banner_role
slug: Web/Accessibility/ARIA/Roles/Banner_role
locale: en-US
modified: 2019-09-05T11:08:19.123Z
mdn_contributors:
  - seizo3
  - chrisdavidmills
  - Konrud
  - mdnwebdocs-bot
  - PoziWorld
  - ericwbailey
  - estelle
  - thenoelman
  - Dzordzu
  - BenoitL
  - Sheppy
  - hhillen
