title: WAI-ARIA Roles
mdn_url: /ko/docs/Web/Accessibility/ARIA/Roles
slug: Web/Accessibility/ARIA/Roles
locale: ko
modified: 2019-03-18T16:24:18.888Z
mdn_contributors:
  - mdnwebdocs-bot
  - estelle
parent:
  slug: Web/Accessibility/ARIA/Roles
  locale: en-US
  modified: 2019-09-05T06:04:56.508Z
