title: ROLE_OPTION
mdn_url: /en-US/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_OPTION
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_OPTION
locale: en-US
modified: 2019-04-23T14:05:07.830Z
mdn_contributors:
  - wbamberg
  - ExE-Boss
  - mdnwebdocs-bot
  - Sheppy
  - Michael Evil
