title: ROLE_COMBOBOX_LIST
mdn_url: /ja/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_COMBOBOX_LIST
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_COMBOBOX_LIST
locale: ja
modified: 2019-04-25T13:07:39.633Z
mdn_contributors:
  - wbamberg
  - mdnwebdocs-bot
  - shide55
parent:
  slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_COMBOBOX_LIST
  locale: en-US
  modified: 2019-04-23T14:04:10.169Z
