title: ROLE GLASS PANE
mdn_url: /en-US/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_GLASS_PANE
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_GLASS_PANE
locale: en-US
modified: 2019-04-23T14:02:43.224Z
mdn_contributors:
  - wbamberg
  - ExE-Boss
  - Sheppy
  - Michael Evil
