title: ROLE LAYERED PANE
mdn_url: /en-US/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_LAYERED_PANE
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_LAYERED_PANE
locale: en-US
modified: 2019-04-23T14:02:54.312Z
mdn_contributors:
  - wbamberg
  - ExE-Boss
  - Sheppy
  - Michael Evil
