title: ROLE_COLUMNHEADER
mdn_url: /ja/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_COLUMNHEADER
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_COLUMNHEADER
locale: ja
modified: 2019-04-25T13:07:36.017Z
mdn_contributors:
  - wbamberg
  - mdnwebdocs-bot
  - Marsf
  - shide55
parent:
  slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_COLUMNHEADER
  locale: en-US
  modified: 2019-04-23T14:04:05.845Z
