title: ROLE PASSWORD TEXT
mdn_url: /ru/docs/Web/Accessibility/AT-APIs/Gecko/Roles/ROLE_PASSWORD_TEXT
slug: Web/Accessibility/AT-APIs/Gecko/Roles/ROLE_PASSWORD_TEXT
locale: ru
modified: 2019-05-02T17:18:42.896Z
mdn_contributors:
  - wbamberg
  - mdnwebdocs-bot
  - Narvasadata
parent:
  slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_PASSWORD_TEXT
  locale: en-US
  modified: 2019-04-23T14:03:04.679Z
