title: ROLE_TOOLBAR
mdn_url: /en-US/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_TOOLBAR
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_TOOLBAR
locale: en-US
modified: 2019-04-23T14:05:59.984Z
mdn_contributors:
  - wbamberg
  - ExE-Boss
  - mdnwebdocs-bot
  - Sheppy
  - Surkov.alexander
  - Michael Evil
