title: ROLE SECTION
mdn_url: /en-US/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_SECTION
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_SECTION
locale: en-US
modified: 2019-04-23T14:03:11.068Z
mdn_contributors:
  - wbamberg
  - ExE-Boss
  - Sheppy
  - Michael Evil
