title: 'ARIA: switch ロール'
mdn_url: /ja/docs/Web/Accessibility/ARIA/Roles/Switch_role
slug: Web/Accessibility/ARIA/Roles/Switch_role
locale: ja
modified: 2019-03-18T16:22:32.933Z
mdn_contributors:
  - mdnwebdocs-bot
  - Wind1808
parent:
  slug: Web/Accessibility/ARIA/Roles/Switch_role
  locale: en-US
  modified: 2019-11-01T04:24:57.527Z
