title: ROLE_GRIP
mdn_url: /ja/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_GRIP
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_GRIP
locale: ja
modified: 2019-04-25T13:08:09.905Z
mdn_contributors:
  - wbamberg
  - mdnwebdocs-bot
  - Marsf
  - shide55
parent:
  slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_GRIP
  locale: en-US
  modified: 2019-04-23T14:04:40.034Z
