title: ROLE_ROW
mdn_url: /ja/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_ROW
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_ROW
locale: ja
modified: 2019-04-25T13:09:01.651Z
mdn_contributors:
  - wbamberg
  - mdnwebdocs-bot
  - Marsf
  - shide55
parent:
  slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_ROW
  locale: en-US
  modified: 2019-04-23T14:05:30.923Z
