title: ROLE_ARROW
mdn_url: /en-US/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_ARROW
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_ARROW
locale: en-US
modified: 2019-04-23T14:03:32.570Z
mdn_contributors:
  - wbamberg
  - ExE-Boss
  - mdnwebdocs-bot
  - Sheppy
  - Michael Evil
