title: ROLE_TITLEBAR
mdn_url: /en-US/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_TITLEBAR
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_TITLEBAR
locale: en-US
modified: 2019-04-23T14:05:58.380Z
mdn_contributors:
  - wbamberg
  - ExE-Boss
  - mdnwebdocs-bot
  - Sheppy
  - Surkov.alexander
