title: ROLE_COMBOBOX
mdn_url: /en-US/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_COMBOBOX
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_COMBOBOX
locale: en-US
modified: 2019-04-23T14:04:07.869Z
mdn_contributors:
  - wbamberg
  - ExE-Boss
  - mdnwebdocs-bot
  - Sheppy
  - Michael Evil
