title: ROLE_MENUITEM
mdn_url: /ja/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_MENUITEM
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_MENUITEM
locale: ja
modified: 2019-04-25T13:08:32.856Z
mdn_contributors:
  - wbamberg
  - mdnwebdocs-bot
  - Marsf
  - shide55
parent:
  slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_MENUITEM
  locale: en-US
  modified: 2019-04-23T14:05:02.896Z
