title: ROLE LISTBOX
mdn_url: /en-US/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_LISTBOX
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_LISTBOX
locale: en-US
modified: 2019-04-23T14:02:56.069Z
mdn_contributors:
  - wbamberg
  - ExE-Boss
  - Sheppy
  - Michael Evil
