title: ROLE HTML CONTAINER
mdn_url: /en-US/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_HTML_CONTAINER
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_HTML_CONTAINER
locale: en-US
modified: 2019-04-23T14:02:48.538Z
mdn_contributors:
  - wbamberg
  - ExE-Boss
  - Sheppy
  - Michael Evil
