title: 'ARIA: button role'
mdn_url: /en-US/docs/Web/Accessibility/ARIA/Roles/button_role
slug: Web/Accessibility/ARIA/Roles/button_role
locale: en-US
modified: 2019-12-18T05:28:09.249Z
mdn_contributors:
  - brennanyoung
  - chrisnager
  - chrisdavidmills
  - Sheppy
  - dfrase
  - mdnwebdocs-bot
  - oskaroldorf
  - gaurav5430
  - frmbelz
  - marwonline
  - scottaohara
  - uxuf
  - estelle
  - irenesmith
  - skippednote
  - yatil
  - MattyR395
  - Volker-E
  - anastasialanz
  - anpa
  - Maxlufs
  - chain
  - SphinxKnight
  - PushpitaPikuDey
  - Hywan
  - spicyj
  - johansst
  - smarvin
  - Charlotteis
  - AntouanK
  - Adritek
  - ericmsuzanne
  - avryl
  - Herbert.Peters
  - hhillen
