title: ROLE LABEL
mdn_url: /en-US/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_LABEL
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_LABEL
locale: en-US
modified: 2019-04-23T14:02:52.483Z
mdn_contributors:
  - wbamberg
  - ExE-Boss
  - mdnwebdocs-bot
  - Sheppy
  - Michael Evil
