title: ROLE_GRAPHIC
mdn_url: /en-US/docs/Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_GRAPHIC
slug: Mozilla/Tech/Accessibility/AT-APIs/Gecko/Roles/ROLE_GRAPHIC
locale: en-US
modified: 2019-04-23T14:04:38.168Z
mdn_contributors:
  - wbamberg
  - ExE-Boss
  - mdnwebdocs-bot
  - Sheppy
  - kscarfone
  - ethertank
  - Taken
  - Michael Evil
